export const UPDATE_ORG_SETT_REQUEST = 'UPDATE_ORG_SETT_REQUEST';
export const UPDATE_ORG_SETT_SUCCESS = 'UPDATE_ORG_SETT_SUCCESS';
export const UPDATE_ORG_SETT_FAILURE = 'UPDATE_ORG_SETT_FAILURE';

export const GET_ORG_SET_REQUEST = 'GET_ORG_SET_REQUEST';
export const GET_ORG_SET_SUCCESS = 'GET_ORG_SET_SUCCESS';
export const GET_ORG_SET_FAILURE = 'GET_ORG_SET_FAILURE';