
export const GET_WORK_CALENDAR_SUMMARY_REQUEST = 'GET_WORK_CALENDAR_SUMMARY_REQUEST';
export const GET_WORK_CALENDAR_SUMMARY_SUCCESS = 'GET_WORK_CALENDAR_SUMMARY_SUCCESS';
export const GET_WORK_CALENDAR_SUMMARY_FAILURE = 'GET_WORK_CALENDAR_SUMMARY_FAILURE';

export const UPDATE_WORK_CALENDAR_STATUS_REQUEST = 'UPDATE_WORK_CALENDAR_STATUS_REQUEST';
export const UPDATE_WORK_CALENDAR_STATUS_SUCCESS = 'UPDATE_WORK_CALENDAR_STATUS_SUCCESS';
export const UPDATE_WORK_CALENDAR_STATUS_FAILURE = 'UPDATE_WORK_CALENDAR_STATUS_FAILURE';