export const ADD_ORGANIZATION_REQUEST = 'ADD_ORGANIZATION_REQUEST';
export const ADD_ORGANIZATION_SUCCESS = 'ADD_ORGANIZATION_SUCCESS';
export const ADD_ORGANIZATION_FAILURE = 'ADD_ORGANIZATION_FAILURE';


export const GET_ORGANIZATION_DETAIL_REQUEST = 'GET_ORGANIZATION_DETAIL_REQUEST';
export const GET_ORGANIZATION_DETAIL_SUCCESS = 'GET_ORGANIZATION_DETAIL_SUCCESS';
export const GET_ORGANIZATION_DETAIL_FAILURE = 'GET_ORGANIZATION_DETAIL_FAILURE';

export const GET_ORGANIZATION_LIST_REQUEST = 'GET_ORGANIZATION_LIST_REQUEST';
export const GET_ORGANIZATION_LIST_SUCCESS = 'GET_ORGANIZATION_LIST_SUCCESS';
export const GET_ORGANIZATION_LIST_FAILURE = 'GET_ORGANIZATION_LIST_FAILURE';

export const ADD_ORGANIZATION_POLICY_REQUEST = 'ADD_ORGANIZATION_POLICY_REQUEST';
export const ADD_ORGANIZATION_POLICY_SUCCESS = 'ADD_ORGANIZATION_POLICY_SUCCESS';
export const ADD_ORGANIZATION_POLICY_FAILURE = 'ADD_ORGANIZATION_POLICY_FAILURE';

export const GET_WORK_LOCATION_LIST_REQUEST = 'GET_WORK_LOCATION_LIST_REQUEST';
export const GET_WORK_LOCATION_LIST_SUCCESS = 'GET_WORK_LOCATION_LIST_SUCCESS';
export const GET_WORK_LOCATION_LIST_FAILURE = 'GET_WORK_LOCATION_LIST_FAILURE';


export const GET_WORK_LOCATION_DETAIL_REQUEST = 'GET_WORK_LOCATION_DETAIL_REQUEST';
export const GET_WORK_LOCATION_DETAIL_SUCCESS = 'GET_WORK_LOCATION_DETAIL_SUCCESS';
export const GET_WORK_LOCATION_DETAIL_FAILURE = 'GET_WORK_LOCATION_DETAIL_FAILURE';


export const ADD_WORK_LOCATION_REQUEST = 'ADD_WORK_LOCATION_REQUEST';
export const ADD_WORK_LOCATION_SUCCESS = 'ADD_WORK_LOCATION_SUCCESS';
export const ADD_WORK_LOCATION_FAILURE = 'ADD_WORK_LOCATION_FAILURE';


export const UPDATE_ORG_STATUS_REQUEST = 'UPDATE_ORG_STATUS_REQUEST';
export const UPDATE_ORG_STATUS_SUCCESS = 'UPDATE_ORG_STATUS_SUCCESS';
export const UPDATE_ORG_STATUS_FAILURE = 'UPDATE_ORG_STATUS_FAILURE';


