export const GET_LEAVE_TRACKER_REQUEST = 'GET_LEAVE_TRACKER_REQUEST';
export const GET_LEAVE_TRACKER_SUCCESS = 'GET_LEAVE_TRACKER_SUCCESS';
export const GET_LEAVE_TRACKER_FAILURE = 'GET_LEAVE_TRACKER_FAILURE';

export const GET_EMPLOYEE_ATTRITION_REQUEST = 'GET_EMPLOYEE_ATTRITION_REQUEST';
export const GET_EMPLOYEE_ATTRITION_SUCCESS = 'GET_EMPLOYEE_ATTRITION_SUCCESS';
export const GET_EMPLOYEE_ATTRITION_FAILURE = 'GET_EMPLOYEE_ATTRITION_FAILURE';