export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_TODAY_ATTENDANCE_DETAIL_REQUEST = 'GET_TODAY_ATTENDANCE_DETAIL_REQUEST';
export const GET_TODAY_ATTENDANCE_DETAIL_SUCCESS = 'GET_TODAY_ATTENDANCE_DETAIL_SUCCESS';
export const GET_TODAY_ATTENDANCE_DETAIL_FAILURE = 'GET_TODAY_ATTENDANCE_DETAIL_FAILURE';

export const ADD_ATTENDANCE_PUNCH_REQUEST = 'ADD_ATTENDANCE_PUNCH_REQUEST';
export const ADD_ATTENDANCE_PUNCH_SUCCESS = 'ADD_ATTENDANCE_PUNCH_SUCCESS';
export const ADD_ATTENDANCE_PUNCH_FAILURE = 'ADD_ATTENDANCE_PUNCH_FAILURE';