export const GET_EMPLOYEESTATS_SUMMARY_REQUEST = 'GET_EMPLOYEESTATS_SUMMARY_REQUEST';
export const GET_EMPLOYEESTATS_SUMMARY_SUCCESS = 'GET_EMPLOYEESTATS_SUMMARY_SUCCESS';
export const GET_EMPLOYEESTATS_SUMMARY_FAILURE = 'GET_EMPLOYEESTATS_SUMMARY_FAILURE';

export const GET_PERFORMANCE_REQUEST = 'GET_PERFORMANCE_REQUEST';
export const GET_PERFORMANCE_SUCCESS = 'GET_PERFORMANCE_SUCCESS';
export const GET_PERFORMANCE_FAILURE = 'GET_PERFORMANCE_FAILURE';

export const GET_DAILYATTENDANCE_REQUEST = 'GET_DAILYATTENDANCE_REQUEST';
export const GET_DAILYATTENDANCE_SUCCESS = 'GET_DAILYATTENDANCEE_SUCCESS';
export const GET_DAILYATTENDANCE_FAILURE = 'GET_DAILYATTENDANCE_FAILURE';



// /////////////old/////////////////////// //
export const GET_ORGANIZATION_DEPARTMENT_SUMMARY_REQUEST = 'GET_ORGANIZATION_DEPARTMENT_SUMMARY_REQUEST';
export const GET_ORGANIZATION_DEPARTMENT_SUMMARY_SUCCESS = 'GET_ORGANIZATION_DEPARTMENT_SUMMARY_SUCCESS';
export const GET_ORGANIZATION_DEPARTMENT_SUMMARY_FAILURE = 'GET_ORGANIZATION_DEPARTMENT_SUMMARY_FAILURE';


export const GET_ORGANIZATION_DESIGNATION_SUMMARY_REQUEST = 'GET_ORGANIZATION_DESIGNATION_SUMMARY_REQUEST';
export const GET_ORGANIZATION_DESIGNATION_SUMMARY_SUCCESS = 'GET_ORGANIZATION_DESIGNATION_SUMMARY_SUCCESS';
export const GET_ORGANIZATION_DESIGNATION_SUMMARY_FAILURE = 'GET_ORGANIZATION_DESIGNATION_SUMMARY_FAILURE';

export const GET_ORGANIZATION_GENDER_REQUEST = 'GET_ORGANIZATION_GENDER_REQUEST';
export const GET_ORGANIZATION_GENDER_SUCCESS = 'GET_ORGANIZATION_GENDER_SUCCESS';
export const GET_ORGANIZATION_GENDER_FAILURE = 'GET_ORGANIZATION_GENDER_FAILURE';


export const GET_ORGANIZATION_AGE_GROUP_REQUEST = 'GET_ORGANIZATION_AGE_GROUP_REQUEST';
export const GET_ORGANIZATION_AGE_GROUP_SUCCESS = 'GET_ORGANIZATION_AGE_GROUP_SUCCESS';
export const GET_ORGANIZATION_AGE_GROUP_FAILURE = 'GET_ORGANIZATION_AGE_GROUP_FAILURE';

export const GET_ORGANIZATION_DashboardOverview_REQUEST = 'GET_ORGANIZATION_DashboardOverview_REQUEST';
export const GET_ORGANIZATION_DashboardOverview_SUCCESS = 'GET_ORGANIZATION_DashboardOverview_SUCCESS';
export const GET_ORGANIZATION_DashboardOverview_FAILURE = 'GET_ORGANIZATION_DashboardOverview_FAILURE';

export const GET_ORGANIZATION_ATTRITION_TREND_REQUEST = 'GET_ORGANIZATION_ATTRITION_TREND_REQUEST';
export const GET_ORGANIZATION_ATTRITION_TREND_SUCCESS = 'GET_ORGANIZATION_ATTRITION_TREND_SUCCESS';
export const GET_ORGANIZATION_ATTRITION_TREND_FAILURE = 'GET_ORGANIZATION_ATTRITION_TREND_FAILURE';

export const GET_ORGANIZATION_ADDITION_TREND_REQUEST = 'GET_ORGANIZATION_ADDITION_TREND_REQUEST';
export const GET_ORGANIZATION_ADDITION_TREND_SUCCESS = 'GET_ORGANIZATION_ADDITION_TREND_SUCCESS';
export const GET_ORGANIZATION_ADDITION_TREND_FAILURE = 'GET_ORGANIZATION_ADDITION_TREND_FAILURE';

export const GET_ORGANIZATION_HEADCOUNT_REQUEST = 'GET_ORGANIZATION_HEADCOUNT_REQUEST';
export const GET_ORGANIZATION_HEADCOUNT_SUCCESS = 'GET_ORGANIZATION_HEADCOUNT_SUCCESS';
export const GET_ORGANIZATION_HEADCOUNT_FAILURE = 'GET_ORGANIZATION_HEADCOUNT_FAILURE';
