export const GET_MY_LEAVE_REPORT_REQUEST = 'GET_MY_LEAVE_REPORT_REQUEST';
export const GET_MY_LEAVE_REPORT_SUCCESS = 'GET_MY_LEAVE_REPORT_SUCCESS';
export const GET_MY_LEAVE_REPORT_FAILURE = 'GET_MY_LEAVE_REPORT_FAILURE';

export const GET_MY_LEAVE_REPORT_YEARLY_REQUEST = 'GET_MY_LEAVE_REPORT_YEARLY_REQUEST';
export const GET_MY_LEAVE_REPORT_YEARLY_SUCCESS = 'GET_MY_LEAVE_REPORT_YEARLY_SUCCESS';
export const GET_MY_LEAVE_REPORT_YEARLY_FAILURE = 'GET_MY_LEAVE_REPORT_YEARLY_FAILURE';

export const GET_MY_LEAVE_SUMMARY_REQUEST = 'GET_MY_LEAVE_SUMMARY_REQUEST';
export const GET_MY_LEAVE_SUMMARY_SUCCESS = 'GET_MY_LEAVE_SUMMARY_SUCCESS';
export const GET_MY_LEAVE_SUMMARY_FAILURE = 'GET_MY_LEAVE_SUMMARY_FAILURE';

export const GET_APPRAISAL_LIST_REQUEST = 'GET_APPRAISAL_LIST_REQUEST';
export const GET_APPRAISAL_LIST_SUCCESS = 'GET_APPRAISAL_LIST_SUCCESS';
export const GET_APPRAISAL_LIST_FAILURE = 'GET_APPRAISAL_LIST_FAILURE';