export const ADD_NEW_MASTER_REQUEST = 'ADD_NEW_MASTER_REQUEST';
export const ADD_NEW_MASTER_SUCCESS = 'ADD_ANNOUNCEMENT_SUCCESS';
export const ADD_NEW_MASTER_FAILURE = 'ADD_ANNOUNCEMENT_FAILURE';

export const GET_MASTER_LIST_REQUEST = 'GET_MASTER_LIST_REQUEST';
export const GET_MASTER_LIST_SUCCESS = 'GET_MASTER_LIST_SUCCESS';
export const GET_MASTER_LIST_FAILURE = 'GET_MASTER_LIST_FAILURE';

export const EDIT_MASTER_REQUEST = 'EDIT_MASTER_REQUEST';
export const EDIT_MASTER_SUCCESS = 'EDIT_MASTER_SUCCESS';
export const EDIT_MASTER_FAILURE = 'EDIT_MASTER_FAILURE';