
export const GET_EMPLOYEE_STATS_REQUEST = 'GET_EMPLOYEE_STATS_REQUEST';
export const GET_EMPLOYEE_STATS_SUCCESS = 'GET_EMPLOYEE_STATS_SUCCESS';
export const GET_EMPLOYEE_STATS_FAILURE = 'GET_EMPLOYEE_STATS_FAILURE';

export const GET_EMP_ATTENDANCE_OVERVIEW_REQUEST = 'GET_EMP_ATTENDANCE_OVERVIEW_REQUEST';
export const GET_EMP_ATTENDANCE_OVERVIEW_SUCCESS = 'GET_EMP_ATTENDANCE_OVERVIEW_SUCCESS';
export const GET_EMP_ATTENDANCE_OVERVIEW_FAILURE = 'GET_EMP_ATTENDANCE_OVERVIEW_FAILURE';

export const GET_NEW_EMP_LIST_REQUEST = 'GET_NEW_EMP_LIST_REQUEST';
export const GET_NEW_EMP_LIST_SUCCESS = 'GET_NEW_EMP_LIST_SUCCESS';
export const GET_NEW_EMP_LIST_FAILURE = 'GET_NEW_EMP_LIST_FAILURE';

export const GET_LEAVE_REPORT_REQUEST = 'GET_LEAVE_REPORT_REQUEST';
export const GET_LEAVE_REPORT_SUCCESS = 'GET_LEAVE_REPORT_SUCCESS';
export const GET_LEAVE_REPORT_FAILURE = 'GET_LEAVE_REPORT_FAILURE';

export const ADD_QUICK_LINK_REQUEST = 'ADD_QUICK_LINK_REQUEST';
export const ADD_QUICK_LINK_SUCCESS = 'ADD_QUICK_LINK_SUCCESS';
export const ADD_QUICK_LINK_FAILURE = 'ADD_QUICK_LINK_FAILURE';

export const GET_QUICK_LINK_LIST_REQUEST = 'GET_QUICK_LINK_LIST_REQUEST';
export const GET_QUICK_LINK_LIST_SUCCESS = 'GET_QUICK_LINK_LIST_SUCCESS';
export const GET_QUICK_LINK_LIST_FAILURE = 'GET_QUICK_LINK_LIST_FAILURE';

export const GET_QUICK_LINK_DETAIL_REQUEST = 'GET_QUICK_LINK_DETAIL_REQUEST';
export const GET_QUICK_LINK_DETAIL_SUCCESS = 'GET_QUICK_LINK_DETAIL_SUCCESS';
export const GET_QUICK_LINK_DETAIL_FAILURE = 'GET_QUICK_LINK_DETAIL_FAILURE';

export const DELETE_QUICK_LINK_REQUEST = 'DELETE_QUICK_LINK_REQUEST';
export const DELETE_QUICK_LINK_SUCCESS = 'DELETE_QUICK_LINK_SUCCESS';
export const DELETE_QUICK_LINK_FAILURE = 'DELETE_QUICK_LINK_FAILURE';