export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';

export const GET_EMPLOYEE_LIST_REQUEST = 'GET_EMPLOYEE_LIST_REQUEST';
export const GET_EMPLOYEE_LIST_SUCCESS = 'GET_EMPLOYEE_LIST_SUCCESS';
export const GET_EMPLOYEE_LIST_FAILURE = 'GET_EMPLOYEE_LIST_FAILURE';

export const GET_EMP_BIRTHDAY_LIST_REQUEST = 'GET_EMP_BIRTHDAY_LIST_REQUEST';
export const GET_EMP_BIRTHDAY_LIST_SUCCESS = 'GET_EMP_BIRTHDAY_LIST_SUCCESS';
export const GET_EMP_BIRTHDAY_LIST_FAILURE = 'GET_EMP_BIRTHDAY_LIST_FAILURE';

export const UPDATE_EMPLOYEE_STATUS_REQUEST = 'UPDATE_EMPLOYEE_STATUS_REQUEST';
export const UPDATE_EMPLOYEE_STATUS_SUCCESS = 'UPDATE_EMPLOYEE_STATUS_SUCCESS';
export const UPDATE_EMPLOYEE_STATUS_FAILURE = 'UPDATE_EMPLOYEE_STATUS_FAILURE';

export const GET_EMPLOYEE_DETAIL_REQUEST = 'GET_EMPLOYEE_DETAIL_REQUEST';
export const GET_EMPLOYEE_DETAIL_SUCCESS = 'GET_EMPLOYEE_DETAIL_SUCCESS';
export const GET_EMPLOYEE_DETAIL_FAILURE = 'GET_EMPLOYEE_DETAIL_FAILURE';

export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAILURE = 'DELETE_EMPLOYEE_FAILURE';

export const ADD_EMP_ADDRESS_REQUEST = 'ADD_EMP_ADDRESS_REQUEST';
export const ADD_EMP_ADDRESS_SUCCESS = 'ADD_EMP_ADDRESS_SUCCESS';
export const ADD_EMP_ADDRESS_FAILURE = 'ADD_EMP_ADDRESS_FAILURE';

export const ADD_EMP_EXPERIENCE_REQUEST = 'ADD_EMP_EXPERIENCE_REQUEST';
export const ADD_EMP_EXPERIENCE_SUCCESS = 'ADD_EMP_EXPERIENCE_SUCCESS';
export const ADD_EMP_EXPERIENCE_FAILURE = 'ADD_EMP_EXPERIENCE_FAILURE';

export const ADD_EMP_EDUCATION_REQUEST = 'ADD_EMP_EDUCATION_REQUEST';
export const ADD_EMP_EDUCATION_SUCCESS = 'ADD_EMP_EDUCATION_SUCCESS';
export const ADD_EMP_EDUCATION_FAILURE = 'ADD_EMP_EDUCATION_FAILURE';

export const ADD_EMP_DOCUMENT_REQUEST = 'ADD_EMP_DOCUMENT_REQUEST';
export const ADD_EMP_DOCUMENT_SUCCESS = 'ADD_EMP_DOCUMENT_SUCCESS';
export const ADD_EMP_DOCUMENT_FAILURE = 'ADD_EMP_DOCUMENT_FAILURE';

export const ADD_EMP_REMARK_REQUEST = 'ADD_EMP_REMARK_REQUEST';
export const ADD_EMP_REMARK_SUCCESS = 'ADD_EMP_REMARK_SUCCESS';
export const ADD_EMP_REMARK_FAILURE = 'ADD_EMP_REMARK_FAILURE';

export const DELETE_EMP_EXPERIENCE_REQUEST = 'DELETE_EMP_EXPERIENCE_REQUEST';
export const DELETE_EMP_EXPERIENCE_SUCCESS = 'DELETE_EMP_EXPERIENCE_SUCCESS';
export const DELETE_EMP_EXPERIENCE_FAILURE = 'DELETE_EMP_EXPERIENCE_FAILURE';

export const DELETE_EMP_EDUCATION_REQUEST = 'DELETE_EMP_EDUCATION_REQUEST';
export const DELETE_EMP_EDUCATION_SUCCESS = 'DELETE_EMP_EDUCATION_SUCCESS';
export const DELETE_EMP_EDUCATION_FAILURE = 'DELETE_EMP_EDUCATION_FAILURE';

export const DELETE_EMP_DOCUMENT_REQUEST = 'DELETE_EMP_DOCUMENT_REQUEST';
export const DELETE_EMP_DOCUMENT_SUCCESS = 'DELETE_EMP_DOCUMENT_SUCCESS';
export const DELETE_EMP_DOCUMENT_FAILURE = 'DELETE_EMP_DOCUMENT_FAILURE';

export const DELETE_EMP_REMARK_REQUEST = 'DELETE_EMP_REMARK_REQUEST';
export const DELETE_EMP_REMARK_SUCCESS = 'DELETE_EMP_REMARK_SUCCESS';
export const DELETE_EMP_REMARK_FAILURE = 'DELETE_EMP_REMARK_FAILURE';

export const IMPORT_EMP_DATA_REQUEST = 'IMPORT_EMP_DATA_REQUEST';
export const IMPORT_EMP_DATA_SUCCESS = 'IMPORT_EMP_DATA_SUCCESS';
export const IMPORT_EMP_DATA_FAILURE = 'IMPORT_EMP_DATA_FAILURE';
