export const GET_USER_BY_ID_REQUEST = 'GET_USER_BY_ID_REQUEST';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_FAILURE = 'GET_USER_BY_ID_FAILURE';

export const FETCH_ALL_DEPARTMENT_LIST_REQUEST = "FETCH_ALL_DEPARTMENT_LIST_REQUEST";
export const FETCH_ALL_DEPARTMENT_LIST_SUCCESS = "FETCH_ALL_DEPARTMENT_LIST_SUCCESS";
export const FETCH_ALL_DEPARTMENT_LIST_FAILURE = "FETCH_ALL_DEPARTMENT_LIST_FAILURE";